### ISSUE TITLE
My Z370 HD3 + i5 8400 connect with hdmi and the screen goes purple/pink. Any idea ?

### ISSUE THREAD

**Issue by zealforbeing** [kinoute/Hack-Z370-HD3P-i5-8400#1]

**Comment by kinoute** [comment]
Hello,

This issue is quite common. The Vanilla guide listed in the README file talks about it. It's easy to fix it. It is caused by the Mac thinking your HDMI port is a DisplayPort. You can see the two solutions for this problem in this page:

https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake

Do the framebuffer solution, it's better. You can see it in my `config.plist` file. But we don't have the exact motherboard so be careful.

**Comment by zealforbeing** [comment]
> Hello,
> 
> This issue is quite common. The Vanilla guide listed in the README file talks about it. It's easy to fix it. It is caused by the Mac thinking your HDMI port is a DisplayPort. You can see the two solutions for this problem in this page:
> 
> https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake
> 
> Do the framebuffer solution, it's better. You can see it in my `config.plist` file. But we don't have the exact motherboard so be careful.

Thanks! I‘ll try.

**Comment by zealforbeing** [comment]
> Hello,
> 
> This issue is quite common. The Vanilla guide listed in the README file talks about it. It's easy to fix it. It is caused by the Mac thinking your HDMI port is a DisplayPort. You can see the two solutions for this problem in this page:
> 
> https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake
> 
> Do the framebuffer solution, it's better. You can see it in my `config.plist` file. But we don't have the exact motherboard so be careful.

It work!!! https://github.com/corpnewt/ForceRGB . I run the script and fixed. I try to change and the DisplayPort type to HDMI but didn't work. 
I got one question is that my status bar can't be opaque. My UHD 630 didn't work well

**Comment by kinoute** [comment]
Check your System Specs ( menu) and check if you VRAM is correctly set to 1536MB for your UHD 630.

**Comment by zealforbeing** [comment]
> Check your System Specs ( menu) and check if you VRAM is correctly set to 1536MB for your UHD 630.

It is 1536MB now.

**Comment by kinoute** [comment]
Can't help you on this one, sorry.

**Comment by zealforbeing** [comment]
> Check your System Specs ( menu) and check if you VRAM is correctly set to 1536MB for your UHD 630.

I add boot arg -disablegfxfirmware and it just work ! Thanks !
