### ISSUE TITLE
Upgrading to Sonoma

### ISSUE THREAD

**Issue by himchawla** [kinoute/Hack-Z370-HD3P-i5-8400#10]
Thanks for your legendary work, Any plans of upgrading to Sonoma?

Edit:
Update worked flawlessly with no changes.

**Comment by kinoute** [comment]
Thanks for noticing me! I was about to say that since we use already the up-to-date OpenCore version and maybe the same for the kexts, it should be fine.

I would to the upgrade in the following weeks, I always wait a little to do so.
