### ISSUE TITLE
Update to Catalina? Audio not working anymore

### ISSUE THREAD

**Issue by michbeck100** [kinoute/Hack-Z370-HD3P-i5-8400#2]
I've followed the instructions and everything was working with Mojave (10.14.6). But after the update to Catalina (10.15.1) the ALC1220 is not working anymore. Did you update, too?

**Comment by kinoute** [comment]
Hello,

Sorry, I haven't updated to Catalina yet as I have some 32-bits audio plugins I use heavily. I can't help you that much on this one. Do the inputs/outputs still appear in the Sound preferences?

You could try to change the the `alcid` boot argument. Right now it is set to 27 in `config.plist`. You can find other layout-id for ALC1220 here: https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

**Comment by michbeck100** [comment]
No inputs/Outputs anymore. I'm still using `alcid=27`. Will report if I find the problem

**Comment by kinoute** [comment]
You could also try to add the boot arguments `-lilubeta -alcbeta`. Be sure to have the latest AppleALC and Lilu kexts though.

**Comment by michbeck100** [comment]
Solved. It was some outdated kexts in `/Library/Extensions` installed by some previous run of MultiBeast. Once I deleted them the audio devices show up again

**Comment by kinoute** [comment]
@michbeck100 Glad to hear. Vanilla install FTW. Cheers.
