### ISSUE TITLE
Network card will be cut off, when continuous download

### ISSUE THREAD

**Issue by bigbigbigfish** [kinoute/Hack-Z370-HD3P-i5-8400#4]
This situation has occurred many times, when the continuous download data reaches about 20GB. At this time, the ping gateway is unreachable, and ping 127.0.0.1 is passable. You can reproduce this problem.
After the problem occurs, you must restart the computer to access the network. It's really depressing, because I can't always watch the download to restart the computer. Not sure if the kext driver is the problem?

Name: ethernet
   Type: Ethernet controller
   Bus: PCI
   Vendor ID: 0x8086
   Device ID: 0x15b8
   Subsystem Vendor ID: 0x1458
   Subsystem ID: 0xe000
   Revision ID: 0x0000
   BSD name: en0
   Kext name: IntelMausiEthernet.kext
   Location: /Library/Extensions/IntelMausiEthernet.kext
   Version: 2.4.0

**Comment by kinoute** [comment]
Hi,

I'm using the 2.5.0 version of IntelMausiEthernet.kext, yours seems to be 2.4.0. 

https://www.insanelymac.com/forum/files/file/396-intelmausiethernet/

**Comment by bigbigbigfish** [comment]
> Hi,
> 
> I'm using the 2.5.0 version of IntelMausiEthernet.kext, yours seems to be 2.4.0.
> 
> https://www.insanelymac.com/forum/files/file/396-intelmausiethernet/

hi，
The EFI CLOVER network card driver we checked is 2.5, but it is not used in the system. Does this need to be installed manually? I installed it manually now, the problem remains to be seen.
But why does the version in CLOVER not take effect?

**Comment by bigbigbigfish** [comment]
The same problem exists, version 2.50.



imac:~ love$ ping 127.0.0.1

PING 127.0.0.1 (127.0.0.1): 56 data bytes

64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.041 ms

64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.086 ms

^C

--- 127.0.0.1 ping statistics ---

2 packets transmitted, 2 packets received, 0.0% packet loss

round-trip min/avg/max/stddev = 0.041/0.064/0.086/0.022 ms

imac:~ love$ ping 192.168.1.1

PING 192.168.1.1 (192.168.1.1): 56 data bytes

ping: sendto: No route to host

Request timeout for icmp_seq 0

ping: sendto: No route to host

Request timeout for icmp_seq 1

ping: sendto: No route to host

Request timeout for icmp_seq 2

^C

**Comment by kinoute** [comment]
Sorry, I don't think I can help you on this one. I have sometimes a problem with my ethernet where I can ping hosts like google but I can't navigate for minutes (either after a cold boot/reboot, either after sleep) but I couldn't find the issue. I disable/enable the service in Preferences/Network and it works again.

I suggest you to install the debug version of the kext, and read the log when the problem appears. You can post the log on the kext's thread on InsanelyMac.

**Comment by kinoute** [comment]
@bigbigbigfish by the way, did you try this version?

https://github.com/acidanthera/IntelMausi/releases

**Comment by bigbigbigfish** [comment]
Not yet. Add video card, in this EFI configuration, burnt out 2 pieces of rx580 continuously! Maybe the sensor doesn't have the data to start the fan cooling.

**Comment by kinoute** [comment]
Did you find a solution? I still have my problem when waking up where I can ping websites but not browse anything. I have to disable/reactivate the Ethernet service in Preferences / Network to make it work.
