### ISSUE TITLE
How to enable IGPU

### ISSUE THREAD

**Issue by maverickchangithub** [kinoute/Hack-Z370-HD3P-i5-8400#5]
would mind telling me how to enable IGPU?
i have a Gigabyte z370-hd3p board , with 1 hdmi 1 dvi and 1 vga port.
tried lot of things ,  the platform id is not quite right, hdmi to will cause purple screen.
thanks

**Comment by kinoute** [comment]
Hi, the purple screen issue is a common issue, have a look at this:

https://github.com/kinoute/Hack-Z370-HD3P-i5-8400/issues/1

**Comment by maverickchangithub** [comment]
thanks for the reply.
Recently i upgrade another machine to Catalina with a amd card.
If it is possible to solve the purple screen problem, it would be great.
Btw, besides the purple screen issue, when in login screen , the mouse will freeze every couple of seconds and i could never get the login being focused.Is it common too?
Anyway , i would try solved it .Maybe i would come back ask more questions.
Thanks!

**Comment by maverickchangithub** [comment]
i tried with success in Catalina! Using intel inject ,platform-id 3e9b0007 which does not work in mojave.
Thanks again!
